// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToQueue(arg1) {
  return window['go']['main']['App']['AddToQueue'](arg1);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function CheckAndInstallDeps() {
  return window['go']['main']['App']['CheckAndInstallDeps']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function FetchVideoInfo(arg1) {
  return window['go']['main']['App']['FetchVideoInfo'](arg1);
}

export function GetDownloadHistory() {
  return window['go']['main']['App']['GetDownloadHistory']();
}

export function GetOutputDir() {
  return window['go']['main']['App']['GetOutputDir']();
}

export function IsValidYouTubeURL(arg1) {
  return window['go']['main']['App']['IsValidYouTubeURL'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function SaveToHistory(arg1) {
  return window['go']['main']['App']['SaveToHistory'](arg1);
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}

export function UpdateYtDlp() {
  return window['go']['main']['App']['UpdateYtDlp']();
}
