// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddToQueue(arg1:main.DownloadTask):Promise<string>;

export function CancelTask(arg1:string):Promise<void>;

export function CheckAndInstallDeps():Promise<void>;

export function ClearHistory():Promise<void>;

export function FetchVideoInfo(arg1:string):Promise<main.VideoInfo>;

export function GetDownloadHistory():Promise<Array<main.DownloadHistory>>;

export function GetOutputDir():Promise<string>;

export function IsValidYouTubeURL(arg1:string):Promise<boolean>;

export function OpenFolder(arg1:string):Promise<void>;

export function SaveToHistory(arg1:main.DownloadHistory):Promise<void>;

export function SelectOutputDir():Promise<string>;

export function UpdateYtDlp():Promise<void>;
