package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/gen2brain/beeep"
	"github.com/lrstanley/go-ytdlp"
	wailsRuntime "github.com/wailsapp/wails/v2/pkg/runtime"
)

// App struct
type App struct {
	ctx context.Context
}

// NewApp creates a new App application struct
func NewApp() *App {
	return &App{}
}

// startup is called when the app starts. The context is saved
// so we can call the runtime methods
func (a *App) startup(ctx context.Context) {
	a.ctx = ctx
}

/* -------------------- Constants -------------------- */

const (
	maxConcurrentDownloads = 3
	progressUpdateInterval = 200 * time.Millisecond
	speedSmoothingAlpha    = 0.2
	taskQueueSize          = 100
	cleanupDelay           = 2 * time.Second
	fetchTimeout           = 30 * time.Second
	fetchDebounceDelay     = 600 * time.Millisecond
	maxRetries             = 3
	retryBaseDelay         = 2 * time.Second
	prefOutputDir          = "output_dir"
	settingsFileName       = "settings.json"
	searchHistoryFileName  = "search_history.json"
	subscriptionsFileName  = "subscriptions.json"
)

/* -------------------- Types -------------------- */

type AppSettings struct {
	DefaultVideoResolution string            `json:"defaultVideoResolution"`
	DefaultAudioFormat     string            `json:"defaultAudioFormat"`
	AutoUpdateYtDlp        bool              `json:"autoUpdateYtDlp"`
	ProxyURL               string            `json:"proxyUrl"`
	Theme                  string            `json:"theme"`
	DownloadSpeedLimit     int               `json:"downloadSpeedLimit"`
	EnableNotifications    bool              `json:"enableNotifications"`
	EnableSoundAlerts      bool              `json:"enableSoundAlerts"`
	MinimizeToTray         bool              `json:"minimizeToTray"`
	EnableClipboardMonitor bool              `json:"enableClipboardMonitor"`
	SubtitleLanguages      []string          `json:"subtitleLanguages"`
	EmbedMetadata          bool              `json:"embedMetadata"`
	GenerateNFO            bool              `json:"generateNfo"`
	OutputTemplate         string            `json:"outputTemplate"`
	OrganizeBy             string            `json:"organizeBy"`
	DuplicateAction        string            `json:"duplicateAction"`
	AutoDownloadSubtitles  bool              `json:"autoDownloadSubtitles"`
	SearchHistoryLimit     int               `json:"searchHistoryLimit"`
	KeyboardShortcuts      map[string]string `json:"keyboardShortcuts"`
}

type SearchResult struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Channel     string `json:"channel"`
	Duration    int    `json:"duration"`
	Thumbnail   string `json:"thumbnail"`
	ViewCount   int64  `json:"viewCount"`
	UploadDate  string `json:"uploadDate"`
	Description string `json:"description"`
	URL         string `json:"url"`
}

type SearchHistory struct {
	Query     string    `json:"query"`
	Timestamp time.Time `json:"timestamp"`
}

type ChannelSubscription struct {
	ChannelID    string    `json:"channelId"`
	ChannelName  string    `json:"channelName"`
	AddedAt      time.Time `json:"addedAt"`
	AutoDownload bool      `json:"autoDownload"`
	LastChecked  time.Time `json:"lastChecked"`
}

type SubtitleInfo struct {
	Language        string `json:"language"`
	LanguageName    string `json:"languageName"`
	Format          string `json:"format"`
	URL             string `json:"url"`
	IsAutoGenerated bool   `json:"isAutoGenerated"`
}

type QueueItem struct {
	TaskID      string       `json:"taskId"`
	Task        DownloadTask `json:"task"`
	Status      string       `json:"status"`
	Progress    float64      `json:"progress"`
	AddedAt     time.Time    `json:"addedAt"`
	StartedAt   *time.Time   `json:"startedAt,omitempty"`
	CompletedAt *time.Time   `json:"completedAt,omitempty"`
	Priority    int          `json:"priority"`
}

type DownloadTask struct {
	URL          string `json:"url"`
	Title        string `json:"title"`
	Type         string `json:"type"`
	Resolution   string `json:"resolution"`
	CleanRes     string `json:"cleanRes"`
	AudioFormat  string `json:"audioFormat"`
	AudioQuality string `json:"audioQuality"`
	VideoCodec   string `json:"videoCodec"`
}

type VideoInfo struct {
	Title       string   `json:"title"`
	Duration    float64  `json:"duration"`
	Resolutions []string `json:"resolutions"`
	IsPlaylist  bool     `json:"isPlaylist"`
	PlaylistID  string   `json:"playlistId,omitempty"`
}

type PlaylistVideo struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Duration int    `json:"duration"`
	URL      string `json:"url"`
}

type PlaylistInfo struct {
	Title      string          `json:"title"`
	ID         string          `json:"id"`
	VideoCount int             `json:"videoCount"`
	Videos     []PlaylistVideo `json:"videos"`
}

type ProgressUpdate struct {
	TaskID  string  `json:"taskId"`
	Percent float64 `json:"percent"`
	Status  string  `json:"status"`
	Speed   string  `json:"speed"`
	ETA     string  `json:"eta"`
	Error   string  `json:"error,omitempty"`
}

type DownloadHistory struct {
	ID           string    `json:"id"`
	URL          string    `json:"url"`
	Title        string    `json:"title"`
	Type         string    `json:"type"`
	Resolution   string    `json:"resolution"`
	AudioFormat  string    `json:"audioFormat"`
	FilePath     string    `json:"filePath"`
	FileSize     int64     `json:"fileSize"`
	DownloadedAt time.Time `json:"downloadedAt"`
	Status       string    `json:"status"`
}

/* -------------------- URL Validation -------------------- */

var youtubeURLPatterns = []*regexp.Regexp{
	regexp.MustCompile(`^(https?://)?(www\.)?(youtube\.com|youtu\.be)/.+`),
	regexp.MustCompile(`^(https?://)?(www\.)?youtube\.com/watch\?v=[\w-]+`),
	regexp.MustCompile(`^(https?://)?(www\.)?youtu\.be/[\w-]+`),
	regexp.MustCompile(`^(https?://)?(www\.)?youtube\.com/shorts/[\w-]+`),
	regexp.MustCompile(`^(https?://)?(www\.)?youtube\.com/live/[\w-]+`),
}

var instagramURLPatterns = []*regexp.Regexp{
	regexp.MustCompile(`^(https?://)?(www\.)?instagram\.com/p/[\w-]+`),
	regexp.MustCompile(`^(https?://)?(www\.)?instagram\.com/reel/[\w-]+`),
	regexp.MustCompile(`^(https?://)?(www\.)?instagram\.com/reels/[\w-]+`),
	regexp.MustCompile(`^(https?://)?(www\.)?instagram\.com/stories/[\w-]+`),
	regexp.MustCompile(`^(https?://)?(www\.)?instagram\.com/tv/[\w-]+`),
	regexp.MustCompile(`^(https?://)?(www\.)?instagram\.com/share/[\w-]+`),
	regexp.MustCompile(`^(https?://)?(www\.)?instagram\.com/share/reel/[\w-]+`),
}

func (a *App) IsValidYouTubeURL(url string) bool {
	for _, pattern := range youtubeURLPatterns {
		if pattern.MatchString(url) {
			return true
		}
	}
	return false
}

func (a *App) IsValidInstagramURL(url string) bool {
	for _, pattern := range instagramURLPatterns {
		if pattern.MatchString(url) {
			return true
		}
	}
	return false
}

func (a *App) IsValidURL(url string) bool {
	return a.IsValidYouTubeURL(url) || a.IsValidInstagramURL(url)
}

func (a *App) IsPlaylistURL(url string) bool {
	playlistPattern := regexp.MustCompile(`[?&]list=([a-zA-Z0-9_-]+)`)
	return playlistPattern.MatchString(url)
}

/* -------------------- Default Settings -------------------- */

func getDefaultSettings() AppSettings {
	return AppSettings{
		DefaultVideoResolution: "1080p",
		DefaultAudioFormat:     "mp3",
		AutoUpdateYtDlp:        true,
		ProxyURL:               "",
		Theme:                  "dark",
		DownloadSpeedLimit:     0,
		EnableNotifications:    true,
		EnableSoundAlerts:      false,
		MinimizeToTray:         true,
		EnableClipboardMonitor: false,
		SubtitleLanguages:      []string{"en"},
		EmbedMetadata:          true,
		GenerateNFO:            false,
		OutputTemplate:         "%(title)s [%(id)s].%(ext)s",
		OrganizeBy:             "flat",
		DuplicateAction:        "warn",
		AutoDownloadSubtitles:  false,
		SearchHistoryLimit:     50,
		KeyboardShortcuts: map[string]string{
			"focusUrl":       "Ctrl+L",
			"startDownload":  "Ctrl+D",
			"cancelDownload": "Escape",
			"toggleTheme":    "Ctrl+T",
		},
	}
}

/* -------------------- Queue System -------------------- */

var (
	taskQueue       = make(chan DownloadTask, taskQueueSize)
	sem             chan struct{}
	semOnce         sync.Once
	activeTasks     = make(map[string]context.CancelFunc)
	tasksMu         sync.RWMutex
	taskCounter     uint64
	historyMu       sync.RWMutex
	settingsMu      sync.RWMutex
	queueMu         sync.RWMutex
	downloadQueue   []*QueueItem
	queuePaused     bool
	speedLimit      int
	currentSettings *AppSettings
)

/* -------------------- Settings Management -------------------- */

func (a *App) getSettingsFilePath() string {
	homeDir, _ := os.UserHomeDir()
	settingsDir := filepath.Join(homeDir, ".predator")
	os.MkdirAll(settingsDir, 0755)
	return filepath.Join(settingsDir, settingsFileName)
}

func (a *App) GetSettings() (AppSettings, error) {
	settingsMu.RLock()
	if currentSettings != nil {
		settings := *currentSettings
		settingsMu.RUnlock()
		return settings, nil
	}
	settingsMu.RUnlock()

	settingsFile := a.getSettingsFilePath()
	data, err := os.ReadFile(settingsFile)
	if err != nil {
		if os.IsNotExist(err) {
			defaults := getDefaultSettings()
			return defaults, nil
		}
		return AppSettings{}, err
	}

	var settings AppSettings
	if err := json.Unmarshal(data, &settings); err != nil {
		return AppSettings{}, err
	}

	settingsMu.Lock()
	currentSettings = &settings
	settingsMu.Unlock()

	return settings, nil
}

func (a *App) SaveSettings(settings AppSettings) error {
	settingsMu.Lock()
	currentSettings = &settings
	settingsMu.Unlock()

	settingsFile := a.getSettingsFilePath()
	data, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return err
	}

	return os.WriteFile(settingsFile, data, 0644)
}

func (a *App) GetDefaultSettings() AppSettings {
	return getDefaultSettings()
}

func (a *App) ResetSettings() error {
	defaults := getDefaultSettings()
	return a.SaveSettings(defaults)
}

/* -------------------- Search History -------------------- */

func (a *App) getSearchHistoryFilePath() string {
	homeDir, _ := os.UserHomeDir()
	historyDir := filepath.Join(homeDir, ".predator")
	return filepath.Join(historyDir, searchHistoryFileName)
}

func (a *App) GetSearchHistory() ([]SearchHistory, error) {
	historyFile := a.getSearchHistoryFilePath()
	data, err := os.ReadFile(historyFile)
	if err != nil {
		if os.IsNotExist(err) {
			return []SearchHistory{}, nil
		}
		return nil, err
	}

	var history []SearchHistory
	if err := json.Unmarshal(data, &history); err != nil {
		return nil, err
	}

	return history, nil
}

func (a *App) AddSearchHistory(query string) error {
	if query == "" {
		return nil
	}

	history, err := a.GetSearchHistory()
	if err != nil {
		return err
	}

	for i, h := range history {
		if h.Query == query {
			history = append(history[:i], history[i+1:]...)
			break
		}
	}

	newEntry := SearchHistory{
		Query:     query,
		Timestamp: time.Now(),
	}
	history = append([]SearchHistory{newEntry}, history...)

	settings, _ := a.GetSettings()
	limit := settings.SearchHistoryLimit
	if limit <= 0 {
		limit = 50
	}
	if len(history) > limit {
		history = history[:limit]
	}

	historyFile := a.getSearchHistoryFilePath()
	data, err := json.MarshalIndent(history, "", "  ")
	if err != nil {
		return err
	}

	return os.WriteFile(historyFile, data, 0644)
}

func (a *App) ClearSearchHistory() error {
	historyFile := a.getSearchHistoryFilePath()
	return os.Remove(historyFile)
}

/* -------------------- YouTube Search -------------------- */

func (a *App) SearchYouTube(query string, filters map[string]string) ([]SearchResult, error) {
	ctx, cancel := context.WithTimeout(context.Background(), fetchTimeout*2)
	defer cancel()

	log.Printf("Searching YouTube for: %s", query)

	searchQuery := fmt.Sprintf("ytsearch10:%s", query)

	a.AddSearchHistory(query)

	result, err := ytdlp.New().
		DumpJSON().
		FlatPlaylist().
		Run(ctx, searchQuery)

	if err != nil {
		log.Printf("Search error: %v", err)
		return nil, fmt.Errorf("search failed: %w", err)
	}

	lines := strings.Split(result.Stdout, "\n")
	results := []SearchResult{}

	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}

		var entry struct {
			ID          string `json:"id"`
			Title       string `json:"title"`
			Channel     string `json:"channel"`
			Duration    int    `json:"duration"`
			Thumbnail   string `json:"thumbnail"`
			ViewCount   int64  `json:"view_count"`
			UploadDate  string `json:"upload_date"`
			Description string `json:"description"`
		}

		if err := json.Unmarshal([]byte(line), &entry); err != nil {
			continue
		}

		if entry.ID == "" {
			continue
		}

		results = append(results, SearchResult{
			ID:          entry.ID,
			Title:       entry.Title,
			Channel:     entry.Channel,
			Duration:    entry.Duration,
			Thumbnail:   entry.Thumbnail,
			ViewCount:   entry.ViewCount,
			UploadDate:  entry.UploadDate,
			Description: entry.Description,
			URL:         fmt.Sprintf("https://youtube.com/watch?v=%s", entry.ID),
		})
	}

	log.Printf("Found %d search results", len(results))
	return results, nil
}

func (a *App) GetTrendingVideos(category string) ([]SearchResult, error) {
	ctx, cancel := context.WithTimeout(context.Background(), fetchTimeout*2)
	defer cancel()

	categoryURLs := map[string]string{
		"music":   "https://www.youtube.com/feed/trending?bp=4gINGgt5dG1hX2NoYXJ0cw%3D%3D",
		"gaming":  "https://www.youtube.com/feed/trending?bp=4gIcGhpnYW1pbmdfY29ycHVzX21vc3RfcG9wdWxhcg%3D%3D",
		"news":    "https://www.youtube.com/feed/trending?bp=4gINcGF0aXNjX3JlbGlldmVz",
		"movies":  "https://www.youtube.com/feed/trending?bp=4gIIY2luZW1hX21vc3RfcG9wdWxhcg%3D%3D",
		"default": "https://www.youtube.com/feed/trending",
	}

	url, ok := categoryURLs[category]
	if !ok {
		url = categoryURLs["default"]
	}

	result, err := ytdlp.New().
		DumpJSON().
		FlatPlaylist().
		PlaylistItems("1-10").
		Run(ctx, url)

	if err != nil {
		return nil, fmt.Errorf("failed to fetch trending: %w", err)
	}

	lines := strings.Split(result.Stdout, "\n")
	results := []SearchResult{}

	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}

		var entry struct {
			ID          string `json:"id"`
			Title       string `json:"title"`
			Channel     string `json:"channel"`
			Duration    int    `json:"duration"`
			Thumbnail   string `json:"thumbnail"`
			ViewCount   int64  `json:"view_count"`
			UploadDate  string `json:"upload_date"`
			Description string `json:"description"`
		}

		if err := json.Unmarshal([]byte(line), &entry); err != nil {
			continue
		}

		if entry.ID == "" {
			continue
		}

		results = append(results, SearchResult{
			ID:          entry.ID,
			Title:       entry.Title,
			Channel:     entry.Channel,
			Duration:    entry.Duration,
			Thumbnail:   entry.Thumbnail,
			ViewCount:   entry.ViewCount,
			UploadDate:  entry.UploadDate,
			Description: entry.Description,
			URL:         fmt.Sprintf("https://youtube.com/watch?v=%s", entry.ID),
		})
	}

	return results, nil
}

/* -------------------- Channel Subscriptions -------------------- */

func (a *App) getSubscriptionsFilePath() string {
	homeDir, _ := os.UserHomeDir()
	subDir := filepath.Join(homeDir, ".predator")
	return filepath.Join(subDir, subscriptionsFileName)
}

func (a *App) GetChannelSubscriptions() ([]ChannelSubscription, error) {
	subFile := a.getSubscriptionsFilePath()
	data, err := os.ReadFile(subFile)
	if err != nil {
		if os.IsNotExist(err) {
			return []ChannelSubscription{}, nil
		}
		return nil, err
	}

	var subs []ChannelSubscription
	if err := json.Unmarshal(data, &subs); err != nil {
		return nil, err
	}

	return subs, nil
}

func (a *App) SubscribeToChannel(channelID, channelName string, autoDownload bool) error {
	subs, err := a.GetChannelSubscriptions()
	if err != nil {
		return err
	}

	for _, sub := range subs {
		if sub.ChannelID == channelID {
			return fmt.Errorf("already subscribed to this channel")
		}
	}

	newSub := ChannelSubscription{
		ChannelID:    channelID,
		ChannelName:  channelName,
		AddedAt:      time.Now(),
		AutoDownload: autoDownload,
		LastChecked:  time.Now(),
	}

	subs = append(subs, newSub)

	subFile := a.getSubscriptionsFilePath()
	data, err := json.MarshalIndent(subs, "", "  ")
	if err != nil {
		return err
	}

	return os.WriteFile(subFile, data, 0644)
}

func (a *App) UnsubscribeFromChannel(channelID string) error {
	subs, err := a.GetChannelSubscriptions()
	if err != nil {
		return err
	}

	newSubs := []ChannelSubscription{}
	for _, sub := range subs {
		if sub.ChannelID != channelID {
			newSubs = append(newSubs, sub)
		}
	}

	subFile := a.getSubscriptionsFilePath()
	data, err := json.MarshalIndent(newSubs, "", "  ")
	if err != nil {
		return err
	}

	return os.WriteFile(subFile, data, 0644)
}

func (a *App) CheckChannelUpdates() ([]SearchResult, error) {
	subs, err := a.GetChannelSubscriptions()
	if err != nil {
		return nil, err
	}

	newVideos := []SearchResult{}

	for _, sub := range subs {
		if !sub.AutoDownload {
			continue
		}

		videos, err := a.GetTrendingVideos("default")
		if err != nil {
			continue
		}

		for _, video := range videos {
			newVideos = append(newVideos, video)
		}
	}

	return newVideos, nil
}

/* -------------------- Notifications -------------------- */

func (a *App) ShowNotification(title, message string) error {
	settings, err := a.GetSettings()
	if err != nil {
		return err
	}

	if !settings.EnableNotifications {
		return nil
	}

	return beeep.Notify(title, message, "")
}

func (a *App) PlaySoundAlert(alertType string) error {
	settings, err := a.GetSettings()
	if err != nil {
		return err
	}

	if !settings.EnableSoundAlerts {
		return nil
	}

	return beeep.Beep(beeep.DefaultFreq, beeep.DefaultDuration)
}

/* -------------------- Clipboard Monitoring -------------------- */

func (a *App) GetClipboardURL() (string, error) {
	return "", nil
}

func (a *App) EnableClipboardMonitor(enabled bool) error {
	settings, err := a.GetSettings()
	if err != nil {
		return err
	}

	settings.EnableClipboardMonitor = enabled
	return a.SaveSettings(settings)
}

/* -------------------- Subtitle Management -------------------- */

func (a *App) GetAvailableSubtitles(url string) ([]SubtitleInfo, error) {
	ctx, cancel := context.WithTimeout(context.Background(), fetchTimeout)
	defer cancel()

	result, err := ytdlp.New().
		DumpJSON().
		ListSubs().
		Run(ctx, url)

	if err != nil {
		return nil, fmt.Errorf("failed to fetch subtitles: %w", err)
	}

	var info struct {
		Subtitles map[string][]struct {
			URL  string `json:"url"`
			Name string `json:"name"`
		} `json:"subtitles"`
		AutomaticCaptions map[string][]struct {
			URL  string `json:"url"`
			Name string `json:"name"`
		} `json:"automatic_captions"`
	}

	if err := json.Unmarshal([]byte(result.Stdout), &info); err != nil {
		return nil, err
	}

	subtitles := []SubtitleInfo{}

	for lang, subs := range info.Subtitles {
		for _, sub := range subs {
			subtitles = append(subtitles, SubtitleInfo{
				Language:        lang,
				LanguageName:    sub.Name,
				Format:          "vtt",
				URL:             sub.URL,
				IsAutoGenerated: false,
			})
		}
	}

	for lang, subs := range info.AutomaticCaptions {
		for _, sub := range subs {
			subtitles = append(subtitles, SubtitleInfo{
				Language:        lang,
				LanguageName:    sub.Name + " (auto)",
				Format:          "vtt",
				URL:             sub.URL,
				IsAutoGenerated: true,
			})
		}
	}

	return subtitles, nil
}

/* -------------------- Duplicate Detection -------------------- */

func (a *App) CheckDuplicate(videoID string) (bool, *DownloadHistory, error) {
	history, err := a.GetDownloadHistory()
	if err != nil {
		return false, nil, err
	}

	for _, item := range history {
		if strings.Contains(item.URL, videoID) {
			return true, &item, nil
		}
	}

	return false, nil, nil
}

/* -------------------- Template & Organization -------------------- */

func (a *App) ValidateTemplate(template string) error {
	invalidChars := []string{"<", ">", ":", "\"", "|", "?", "*"}
	for _, char := range invalidChars {
		if strings.Contains(template, char) {
			return fmt.Errorf("template contains invalid character: %s", char)
		}
	}

	requiredVars := []string{"%(ext)s"}
	for _, v := range requiredVars {
		if !strings.Contains(template, v) {
			return fmt.Errorf("template must contain %s", v)
		}
	}

	return nil
}

func (a *App) PreviewTemplate(template string, videoInfo VideoInfo) (string, error) {
	if err := a.ValidateTemplate(template); err != nil {
		return "", err
	}

	preview := template
	preview = strings.ReplaceAll(preview, "%(title)s", videoInfo.Title)
	preview = strings.ReplaceAll(preview, "%(id)s", "dQw4w9WgXcQ")
	preview = strings.ReplaceAll(preview, "%(ext)s", "mp4")
	preview = strings.ReplaceAll(preview, "%(resolution)s", "1080p")

	return preview, nil
}

func (a *App) GetOrganizedOutputPath(baseDir string, videoInfo VideoInfo, playlistTitle string) (string, error) {
	settings, err := a.GetSettings()
	if err != nil {
		return "", err
	}

	var outputDir string

	switch settings.OrganizeBy {
	case "channel":
		outputDir = filepath.Join(baseDir, "Channels", "Unknown")
	case "playlist":
		if playlistTitle != "" {
			outputDir = filepath.Join(baseDir, "Playlists", sanitizeFilename(playlistTitle))
		} else {
			outputDir = filepath.Join(baseDir, "Singles")
		}
	case "date":
		now := time.Now()
		outputDir = filepath.Join(baseDir, now.Format("2006"), now.Format("01-2006"))
	default:
		outputDir = baseDir
	}

	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return "", err
	}

	return outputDir, nil
}

func sanitizeFilename(name string) string {
	invalid := []string{"<", ">", ":", "\"", "|", "?", "*", "\\", "/"}
	result := name
	for _, char := range invalid {
		result = strings.ReplaceAll(result, char, "_")
	}
	return strings.TrimSpace(result)
}

/* -------------------- Queue Management -------------------- */

func (a *App) GetQueueStatus() ([]QueueItem, error) {
	queueMu.RLock()
	defer queueMu.RUnlock()

	result := make([]QueueItem, len(downloadQueue))
	for i, item := range downloadQueue {
		result[i] = *item
	}
	return result, nil
}

func (a *App) PauseTask(taskID string) error {
	tasksMu.Lock()
	if cancel, ok := activeTasks[taskID]; ok {
		cancel()
		delete(activeTasks, taskID)
	}
	tasksMu.Unlock()

	queueMu.Lock()
	for _, item := range downloadQueue {
		if item.TaskID == taskID {
			item.Status = "paused"
			break
		}
	}
	queueMu.Unlock()

	return nil
}

func (a *App) ResumeTask(taskID string) error {
	queueMu.Lock()
	var task *QueueItem
	for _, item := range downloadQueue {
		if item.TaskID == taskID && item.Status == "paused" {
			task = item
			break
		}
	}
	queueMu.Unlock()

	if task == nil {
		return fmt.Errorf("task not found or not paused")
	}

	task.Status = "queued"
	go a.worker(task.Task, taskID)

	return nil
}

func (a *App) ReorderQueue(taskIDs []string) error {
	queueMu.Lock()
	defer queueMu.Unlock()

	itemMap := make(map[string]*QueueItem)
	for _, item := range downloadQueue {
		itemMap[item.TaskID] = item
	}

	newQueue := make([]*QueueItem, 0, len(taskIDs))
	for i, id := range taskIDs {
		if item, ok := itemMap[id]; ok {
			item.Priority = i
			newQueue = append(newQueue, item)
		}
	}

	downloadQueue = newQueue
	return nil
}

func (a *App) SetSpeedLimit(bytesPerSecond int) error {
	settingsMu.Lock()
	speedLimit = bytesPerSecond
	settingsMu.Unlock()

	settings, err := a.GetSettings()
	if err != nil {
		return err
	}
	settings.DownloadSpeedLimit = bytesPerSecond
	return a.SaveSettings(settings)
}

func (a *App) GetSpeedLimit() int {
	settingsMu.RLock()
	defer settingsMu.RUnlock()
	return speedLimit
}

/* -------------------- History Management -------------------- */

func (a *App) getHistoryFilePath() string {
	homeDir, _ := os.UserHomeDir()
	historyDir := filepath.Join(homeDir, ".predator")
	os.MkdirAll(historyDir, 0755)
	return filepath.Join(historyDir, "history.json")
}

func (a *App) GetDownloadHistory() ([]DownloadHistory, error) {
	historyMu.RLock()
	defer historyMu.RUnlock()

	historyFile := a.getHistoryFilePath()
	data, err := os.ReadFile(historyFile)
	if err != nil {
		if os.IsNotExist(err) {
			return []DownloadHistory{}, nil
		}
		return nil, err
	}

	var history []DownloadHistory
	if err := json.Unmarshal(data, &history); err != nil {
		return nil, err
	}

	for i, j := 0, len(history)-1; i < j; i, j = i+1, j-1 {
		history[i], history[j] = history[j], history[i]
	}

	return history, nil
}

func (a *App) SaveToHistory(item DownloadHistory) error {
	historyMu.Lock()
	defer historyMu.Unlock()

	historyFile := a.getHistoryFilePath()

	var history []DownloadHistory
	data, err := os.ReadFile(historyFile)
	if err == nil {
		json.Unmarshal(data, &history)
	}

	history = append([]DownloadHistory{item}, history...)

	if len(history) > 100 {
		history = history[:100]
	}

	data, err = json.MarshalIndent(history, "", "  ")
	if err != nil {
		return err
	}

	return os.WriteFile(historyFile, data, 0644)
}

func (a *App) OpenFolder(path string) error {
	return nil
}

func (a *App) ClearHistory() error {
	historyMu.Lock()
	defer historyMu.Unlock()

	historyFile := a.getHistoryFilePath()
	return os.Remove(historyFile)
}

func initSemaphore() {
	semOnce.Do(func() {
		sem = make(chan struct{}, maxConcurrentDownloads)
		for i := 0; i < maxConcurrentDownloads; i++ {
			sem <- struct{}{}
		}
	})
}

func (a *App) generateTaskID() string {
	return fmt.Sprintf("task-%d", taskCounter)
}

/* -------------------- Core Methods -------------------- */

func (a *App) CheckAndInstallDeps() error {
	return nil
}

func (a *App) GetOutputDir() string {
	outDir := os.Getenv("PREDATOR_OUTPUT_DIR")
	if outDir == "" {
		outDir, _ := os.Getwd()
		return outDir
	}
	return outDir
}

func (a *App) SelectOutputDir() (string, error) {
	return "", nil
}

func (a *App) FetchVideoInfo(url string) (*VideoInfo, error) {
	ctx, cancel := context.WithTimeout(context.Background(), fetchTimeout)
	defer cancel()

	result, err := ytdlp.New().DumpJSON().Run(ctx, url)
	if err != nil {
		return nil, err
	}

	var info struct {
		Title    string  `json:"title"`
		Duration float64 `json:"duration"`
		Formats  []struct {
			Height         *int   `json:"height"`
			Width          *int   `json:"width"`
			Filesize       *int64 `json:"filesize"`
			FilesizeApprox *int64 `json:"filesize_approx"`
			Vcodec         string `json:"vcodec"`
			Acodec         string `json:"acodec"`
			Ext            string `json:"ext"`
		} `json:"formats"`
	}

	if err := json.Unmarshal([]byte(result.Stdout), &info); err != nil {
		return nil, err
	}

	if info.Title == "" {
		return nil, fmt.Errorf("no video found at URL")
	}

	resMap := make(map[string]string)
	resHeightMap := make(map[int]string)

	for _, f := range info.Formats {
		if f.Vcodec != "none" && f.Height != nil && *f.Height > 0 {
			res := fmt.Sprintf("%dp", *f.Height)
			var size int64 = 0
			if f.Filesize != nil && *f.Filesize > 0 {
				size = *f.Filesize
			} else if f.FilesizeApprox != nil && *f.FilesizeApprox > 0 {
				size = *f.FilesizeApprox
			}

			existingSize := parseSizeString(resMap[res])
			if size > existingSize {
				if size > 0 {
					resMap[res] = formatBytes(float64(size))
					resHeightMap[*f.Height] = formatBytes(float64(size))
				} else {
					resMap[res] = "Unknown"
					resHeightMap[*f.Height] = "Unknown"
				}
			}
		}
	}

	var heights []int
	for h := range resHeightMap {
		heights = append(heights, h)
	}

	for i := 0; i < len(heights); i++ {
		for j := i + 1; j < len(heights); j++ {
			if heights[i] > heights[j] {
				heights[i], heights[j] = heights[j], heights[i]
			}
		}
	}

	opts := []string{}
	for _, h := range heights {
		res := fmt.Sprintf("%dp", h)
		size := resHeightMap[h]
		opts = append(opts, fmt.Sprintf("%s (%s)", res, size))
	}
	opts = append(opts, "best (Unknown)")

	return &VideoInfo{
		Title:       info.Title,
		Duration:    info.Duration,
		Resolutions: opts,
	}, nil
}

func (a *App) FetchPlaylistInfo(url string) (*PlaylistInfo, error) {
	ctx, cancel := context.WithTimeout(context.Background(), fetchTimeout*2)
	defer cancel()

	result, err := ytdlp.New().
		DumpJSON().
		FlatPlaylist().
		Run(ctx, url)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch playlist: %w", err)
	}

	lines := strings.Split(result.Stdout, "\n")

	var playlistTitle, playlistID string
	videos := []PlaylistVideo{}

	for i, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}

		if i == 0 {
			var playlistMeta struct {
				Title   string `json:"title"`
				ID      string `json:"id"`
				Entries []struct {
					ID       string `json:"id"`
					Title    string `json:"title"`
					Duration int    `json:"duration"`
				} `json:"entries"`
			}

			if err := json.Unmarshal([]byte(line), &playlistMeta); err != nil {
				continue
			}

			playlistTitle = playlistMeta.Title
			playlistID = playlistMeta.ID

			for _, entry := range playlistMeta.Entries {
				if entry.ID == "" {
					continue
				}
				videos = append(videos, PlaylistVideo{
					ID:       entry.ID,
					Title:    entry.Title,
					Duration: entry.Duration,
					URL:      fmt.Sprintf("https://youtube.com/watch?v=%s", entry.ID),
				})
			}
			continue
		}

		var entry struct {
			ID            string `json:"id"`
			Title         string `json:"title"`
			Duration      int    `json:"duration"`
			PlaylistID    string `json:"playlist_id"`
			PlaylistTitle string `json:"playlist_title"`
		}

		if err := json.Unmarshal([]byte(line), &entry); err != nil {
			continue
		}

		if playlistID == "" && entry.PlaylistID != "" {
			playlistID = entry.PlaylistID
		}
		if playlistTitle == "" && entry.PlaylistTitle != "" {
			playlistTitle = entry.PlaylistTitle
		}

		if entry.ID == "" {
			continue
		}

		videos = append(videos, PlaylistVideo{
			ID:       entry.ID,
			Title:    entry.Title,
			Duration: entry.Duration,
			URL:      fmt.Sprintf("https://youtube.com/watch?v=%s", entry.ID),
		})
	}

	if playlistID == "" {
		return nil, fmt.Errorf("no playlist found at URL")
	}

	return &PlaylistInfo{
		Title:      playlistTitle,
		ID:         playlistID,
		VideoCount: len(videos),
		Videos:     videos,
	}, nil
}

func (a *App) DownloadPlaylist(videos []PlaylistVideo, downloadType string, resolution string, audioFormat string) ([]string, error) {
	taskIDs := make([]string, 0, len(videos))

	for _, video := range videos {
		videoInfo, err := a.FetchVideoInfo(video.URL)
		if err != nil {
			log.Printf("Failed to fetch info for %s: %v", video.Title, err)
			continue
		}

		cleanRes := ""
		if downloadType == "Video" {
			cleanRes = extractResolution(resolution)
		}

		task := DownloadTask{
			URL:          video.URL,
			Title:        videoInfo.Title,
			Type:         downloadType,
			Resolution:   resolution,
			CleanRes:     cleanRes,
			AudioFormat:  audioFormat,
			AudioQuality: "0",
			VideoCodec:   "",
		}

		taskID, err := a.AddToQueue(task)
		if err != nil {
			log.Printf("Failed to add %s to queue: %v", video.Title, err)
			continue
		}

		taskIDs = append(taskIDs, taskID)
	}

	return taskIDs, nil
}

func (a *App) AddToQueue(task DownloadTask) (string, error) {
	initSemaphore()

	taskID := a.generateTaskID()
	atomic.AddUint64(&taskCounter, 1)

	queueItem := &QueueItem{
		TaskID:   taskID,
		Task:     task,
		Status:   "queued",
		Progress: 0,
		AddedAt:  time.Now(),
		Priority: 0,
	}

	queueMu.Lock()
	downloadQueue = append(downloadQueue, queueItem)
	queueMu.Unlock()

	wailsRuntime.EventsEmit(a.ctx, "task-added", taskID, task)

	go a.worker(task, taskID)

	return taskID, nil
}

func (a *App) CancelTask(taskID string) error {
	tasksMu.Lock()
	if cancel, ok := activeTasks[taskID]; ok {
		cancel()
		delete(activeTasks, taskID)
		tasksMu.Unlock()

		queueMu.Lock()
		for i, item := range downloadQueue {
			if item.TaskID == taskID {
				downloadQueue = append(downloadQueue[:i], downloadQueue[i+1:]...)
				break
			}
		}
		queueMu.Unlock()

		wailsRuntime.EventsEmit(a.ctx, "task-cancelled", taskID)
		return nil
	}
	tasksMu.Unlock()
	return fmt.Errorf("task not found")
}

func (a *App) worker(task DownloadTask, taskID string) {
	initSemaphore()

	<-sem
	defer func() { sem <- struct{}{} }()

	ctx, cancel := context.WithCancel(context.Background())
	tasksMu.Lock()
	activeTasks[taskID] = cancel
	tasksMu.Unlock()

	queueMu.Lock()
	for _, item := range downloadQueue {
		if item.TaskID == taskID {
			now := time.Now()
			item.Status = "downloading"
			item.StartedAt = &now
			break
		}
	}
	queueMu.Unlock()

	wailsRuntime.EventsEmit(a.ctx, "task-started", taskID)

	err := a.downloadWithProgress(ctx, task, taskID)

	tasksMu.Lock()
	delete(activeTasks, taskID)
	tasksMu.Unlock()

	queueMu.Lock()
	for _, item := range downloadQueue {
		if item.TaskID == taskID {
			now := time.Now()
			item.CompletedAt = &now
			if err != nil {
				item.Status = "error"
			} else {
				item.Status = "completed"
				item.Progress = 100
			}
			break
		}
	}
	queueMu.Unlock()

	if err != nil {
		if err == context.Canceled {
			wailsRuntime.EventsEmit(a.ctx, "task-cancelled", taskID)
		} else {
			errStr := err.Error()
			if strings.Contains(errStr, "codec") ||
				strings.Contains(errStr, "merge") ||
				strings.Contains(errStr, "ffmpeg") ||
				strings.Contains(errStr, "postprocessor") {
				wailsRuntime.EventsEmit(a.ctx, "task-error", taskID, "Failed: codec/merge error. Try lower resolution.")
			} else {
				wailsRuntime.EventsEmit(a.ctx, "task-error", taskID, truncateError(err.Error(), 50))
			}
		}
	} else {
		wailsRuntime.EventsEmit(a.ctx, "task-completed", taskID, task)

		var actualFilePath string
		var fileSize int64

		outDir := a.GetOutputDir()
		pattern := filepath.Join(outDir, "*"+strings.ReplaceAll(task.Title, " ", "*")+"*")
		if files, err := filepath.Glob(pattern); err == nil && len(files) > 0 {
			var largestFile string
			var largestSize int64
			for _, f := range files {
				if info, err := os.Stat(f); err == nil && !info.IsDir() {
					if info.Size() > largestSize {
						largestSize = info.Size()
						largestFile = f
					}
				}
			}
			if largestFile != "" {
				actualFilePath = largestFile
				fileSize = largestSize
			}
		}

		if actualFilePath == "" {
			if entries, err := os.ReadDir(outDir); err == nil {
				var mostRecentFile string
				var mostRecentTime time.Time
				for _, entry := range entries {
					if !entry.IsDir() {
						info, err := entry.Info()
						if err == nil {
							if info.ModTime().After(mostRecentTime) {
								mostRecentTime = info.ModTime()
								mostRecentFile = filepath.Join(outDir, entry.Name())
							}
						}
					}
				}
				if mostRecentFile != "" {
					actualFilePath = mostRecentFile
					if info, err := os.Stat(mostRecentFile); err == nil {
						fileSize = info.Size()
					}
				}
			}
		}

		historyItem := DownloadHistory{
			ID:           taskID,
			URL:          task.URL,
			Title:        task.Title,
			Type:         task.Type,
			Resolution:   task.Resolution,
			AudioFormat:  task.AudioFormat,
			FilePath:     actualFilePath,
			FileSize:     fileSize,
			DownloadedAt: time.Now(),
			Status:       "completed",
		}

		a.SaveToHistory(historyItem)
	}
}

func (a *App) downloadWithProgress(ctx context.Context, task DownloadTask, taskID string) error {
	outDir := a.GetOutputDir()

	var formatStr string
	if task.Type == "Video" {
		formatStr = buildVideoFormatString(task.CleanRes, true)
	} else {
		formatStr = buildAudioFormatString(task.AudioFormat)
	}

	dl := ytdlp.New().
		Format(formatStr).
		Output(filepath.Join(outDir, "%(title)s [%(id)s].%(ext)s")).
		ProgressFunc(progressUpdateInterval, func(p ytdlp.ProgressUpdate) {
			percent := p.Percent()

			eta := "Unknown"
			if p.ETA() > 0 {
				eta = formatETA(p.ETA())
			}

			update := ProgressUpdate{
				TaskID:  taskID,
				Percent: percent,
				Status:  "downloading",
				Speed:   "Unknown",
				ETA:     eta,
			}

			wailsRuntime.EventsEmit(a.ctx, "progress-update", update)

			queueMu.Lock()
			for _, item := range downloadQueue {
				if item.TaskID == taskID {
					item.Progress = percent
					break
				}
			}
			queueMu.Unlock()
		})

	if task.Type == "Audio" && task.AudioFormat == "mp3" {
		dl = dl.ExtractAudio().AudioFormat("mp3")
	} else if task.Type == "Audio" && task.AudioFormat == "wav" {
		dl = dl.ExtractAudio().AudioFormat("wav")
	}

	result, err := dl.Run(ctx, task.URL)
	if err != nil {
		return fmt.Errorf("download failed: %w (output: %s)", err, result.Stderr)
	}

	return nil
}

func formatBytes(b float64) string {
	const unit = 1024
	if b < unit {
		return fmt.Sprintf("%.0f B", b)
	}
	div, exp := float64(unit), 0
	for n := b / unit; n >= unit; n /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %ciB", b/div, "KMGT"[exp])
}

func formatETA(d time.Duration) string {
	s := int64(d.Seconds())
	h := s / 3600
	m := (s % 3600) / 60
	sec := s % 60
	if h > 0 {
		return fmt.Sprintf("%02d:%02d:%02d", h, m, sec)
	}
	return fmt.Sprintf("%02d:%02d", m, sec)
}

func formatSpeed(speed float64) string {
	return formatBytes(speed) + "/s"
}

func parseSizeString(sizeStr string) int64 {
	if sizeStr == "" || sizeStr == "Unknown" {
		return 0
	}
	sizeStr = strings.TrimPrefix(sizeStr, "~")
	re := regexp.MustCompile(`([\d.]+)\s*([KMGT]?)i?B`)
	matches := re.FindStringSubmatch(sizeStr)
	if len(matches) < 3 {
		return 0
	}
	val, err := strconv.ParseFloat(matches[1], 64)
	if err != nil {
		return 0
	}
	multiplier := float64(1024)
	switch matches[2] {
	case "K":
		multiplier = 1024
	case "M":
		multiplier = 1024 * 1024
	case "G":
		multiplier = 1024 * 1024 * 1024
	case "T":
		multiplier = 1024 * 1024 * 1024 * 1024
	default:
		multiplier = 1
	}
	return int64(val * multiplier)
}

func truncateError(err string, maxLen int) string {
	if len(err) <= maxLen {
		return err
	}
	return err[:maxLen] + "..."
}

func extractResolution(resolution string) string {
	re := regexp.MustCompile(`^(\d+)p`)
	matches := re.FindStringSubmatch(resolution)
	if len(matches) > 1 {
		return matches[1]
	}
	if strings.HasPrefix(resolution, "best") {
		return "best"
	}
	return ""
}

func buildVideoFormatString(cleanRes string, preferH264 bool) string {
	if cleanRes == "best" {
		return "bestvideo[vcodec^=avc1]+bestaudio[ext=m4a]/" +
			"bestvideo[vcodec^=avc1]+bestaudio[acodec^=mp4a]/" +
			"bestvideo[vcodec^=vp9]+bestaudio[ext=m4a]/" +
			"bestvideo[vcodec^=vp9]+bestaudio[acodec^=mp4a]/" +
			"bestvideo[vcodec^=av01]+bestaudio[ext=m4a]/" +
			"bestvideo[vcodec^=av01]+bestaudio[acodec^=mp4a]/" +
			"bestvideo+bestaudio[ext=m4a]/" +
			"bestvideo+bestaudio[acodec^=mp4a]/" +
			"bestvideo+bestaudio/best"
	}

	resNum, _ := strconv.Atoi(cleanRes)
	if resNum >= 1440 {
		return fmt.Sprintf(
			"bestvideo[vcodec^=avc1][height=%s]+bestaudio[ext=m4a]/"+
				"bestvideo[vcodec^=avc1][height=%s]+bestaudio[acodec^=mp4a]/"+
				"bestvideo[vcodec^=vp9][height=%s]+bestaudio[ext=m4a]/"+
				"bestvideo[vcodec^=vp9][height=%s]+bestaudio[acodec^=mp4a]/"+
				"bestvideo[vcodec^=av01][height=%s]+bestaudio[ext=m4a]/"+
				"bestvideo[vcodec^=av01][height=%s]+bestaudio[acodec^=mp4a]/"+
				"bestvideo[vcodec^=avc1][height<=%s]+bestaudio[ext=m4a]/"+
				"bestvideo[vcodec^=avc1][height<=%s]+bestaudio[acodec^=mp4a]/"+
				"bestvideo[vcodec^=vp9][height<=%s]+bestaudio[ext=m4a]/"+
				"bestvideo[vcodec^=vp9][height<=%s]+bestaudio[acodec^=mp4a]/"+
				"bestvideo[vcodec^=av01][height<=%s]+bestaudio[ext=m4a]/"+
				"bestvideo[vcodec^=av01][height<=%s]+bestaudio[acodec^=mp4a]/"+
				"bestvideo[height<=%s]+bestaudio[ext=m4a]/"+
				"bestvideo[height<=%s]+bestaudio[acodec^=mp4a]/"+
				"best[height<=%s]",
			cleanRes, cleanRes, cleanRes, cleanRes, cleanRes, cleanRes,
			cleanRes, cleanRes, cleanRes, cleanRes, cleanRes, cleanRes,
			cleanRes, cleanRes, cleanRes,
		)
	}

	return fmt.Sprintf(
		"bestvideo[vcodec^=avc1][height=%s]+bestaudio[ext=m4a]/"+
			"bestvideo[vcodec^=avc1][height=%s]+bestaudio[acodec^=mp4a]/"+
			"bestvideo[vcodec^=vp9][height=%s]+bestaudio[ext=m4a]/"+
			"bestvideo[vcodec^=vp9][height=%s]+bestaudio[acodec^=mp4a]/"+
			"bestvideo[vcodec^=av01][height=%s]+bestaudio[ext=m4a]/"+
			"bestvideo[vcodec^=av01][height=%s]+bestaudio[acodec^=mp4a]/"+
			"bestvideo[vcodec^=avc1][height<=%s]+bestaudio[ext=m4a]/"+
			"bestvideo[vcodec^=avc1][height<=%s]+bestaudio[acodec^=mp4a]/"+
			"bestvideo[vcodec^=vp9][height<=%s]+bestaudio[ext=m4a]/"+
			"bestvideo[vcodec^=vp9][height<=%s]+bestaudio[acodec^=mp4a]/"+
			"bestvideo[vcodec^=av01][height<=%s]+bestaudio[ext=m4a]/"+
			"bestvideo[vcodec^=av01][height<=%s]+bestaudio[acodec^=mp4a]/"+
			"bestvideo[height<=%s]+bestaudio[ext=m4a]/"+
			"bestvideo[height<=%s]+bestaudio[acodec^=mp4a]/"+
			"best[height<=%s]",
		cleanRes, cleanRes, cleanRes, cleanRes, cleanRes, cleanRes,
		cleanRes, cleanRes, cleanRes, cleanRes, cleanRes, cleanRes,
		cleanRes, cleanRes, cleanRes,
	)
}

func buildAudioFormatString(format string) string {
	switch format {
	case "m4a":
		return "bestaudio[ext=m4a]/bestaudio[acodec^=mp4a]/bestaudio/best"
	case "opus":
		return "bestaudio[ext=webm][acodec^=opus]/bestaudio[acodec^=opus]/bestaudio/best"
	case "mp3":
		return "bestaudio/best"
	case "wav":
		return "bestaudio/best"
	default:
		return "bestaudio/best"
	}
}
