// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddToQueue(arg1:main.DownloadTask):Promise<string>;

export function CancelTask(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CheckAndInstallDeps():Promise<void>;

export function CheckDuplicate(arg1:string):Promise<Record<string, any>>;

export function ClearHistory():Promise<void>;

export function DownloadPlaylist(arg1:Array<main.PlaylistVideo>,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;

export function ExtractVideoID(arg1:string):Promise<string>;

export function FetchPlaylistInfo(arg1:string):Promise<main.PlaylistInfo>;

export function FetchVideoInfo(arg1:string):Promise<main.VideoInfo>;

export function GetDefaultSettings():Promise<main.Settings>;

export function GetDownloadHistory():Promise<Array<main.DownloadHistory>>;

export function GetOutputDir():Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function InstallWithProgress():Promise<void>;

export function IsInstagramURL(arg1:string):Promise<boolean>;

export function IsM3U8URL(arg1:string):Promise<boolean>;

export function IsPlaylistURL(arg1:string):Promise<boolean>;

export function IsValidInstagramURL(arg1:string):Promise<boolean>;

export function IsValidURL(arg1:string):Promise<boolean>;

export function IsValidXURL(arg1:string):Promise<boolean>;

export function IsValidYouTubeURL(arg1:string):Promise<boolean>;

export function OpenFolder(arg1:string):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SaveToHistory(arg1:main.DownloadHistory):Promise<void>;

export function SelectOutputDir():Promise<string>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function UpdateYtDlp():Promise<void>;
