// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToQueue(arg1) {
  return window['go']['main']['App']['AddToQueue'](arg1);
}

export function CancelTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['CancelTask'](arg1, arg2, arg3);
}

export function CheckAndInstallDeps() {
  return window['go']['main']['App']['CheckAndInstallDeps']();
}

export function CheckDuplicate(arg1) {
  return window['go']['main']['App']['CheckDuplicate'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DownloadPlaylist(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadPlaylist'](arg1, arg2, arg3, arg4);
}

export function ExtractVideoID(arg1) {
  return window['go']['main']['App']['ExtractVideoID'](arg1);
}

export function FetchPlaylistInfo(arg1) {
  return window['go']['main']['App']['FetchPlaylistInfo'](arg1);
}

export function FetchVideoInfo(arg1) {
  return window['go']['main']['App']['FetchVideoInfo'](arg1);
}

export function GetDefaultSettings() {
  return window['go']['main']['App']['GetDefaultSettings']();
}

export function GetDownloadHistory() {
  return window['go']['main']['App']['GetDownloadHistory']();
}

export function GetOutputDir() {
  return window['go']['main']['App']['GetOutputDir']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function InstallWithProgress() {
  return window['go']['main']['App']['InstallWithProgress']();
}

export function IsInstagramURL(arg1) {
  return window['go']['main']['App']['IsInstagramURL'](arg1);
}

export function IsM3U8URL(arg1) {
  return window['go']['main']['App']['IsM3U8URL'](arg1);
}

export function IsPlaylistURL(arg1) {
  return window['go']['main']['App']['IsPlaylistURL'](arg1);
}

export function IsValidInstagramURL(arg1) {
  return window['go']['main']['App']['IsValidInstagramURL'](arg1);
}

export function IsValidURL(arg1) {
  return window['go']['main']['App']['IsValidURL'](arg1);
}

export function IsValidXURL(arg1) {
  return window['go']['main']['App']['IsValidXURL'](arg1);
}

export function IsValidYouTubeURL(arg1) {
  return window['go']['main']['App']['IsValidYouTubeURL'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveToHistory(arg1) {
  return window['go']['main']['App']['SaveToHistory'](arg1);
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}

export function UpdateYtDlp() {
  return window['go']['main']['App']['UpdateYtDlp']();
}
